version: '3.8'

services:

  mongo: 
    image: mongo:latest
    container_name: mongodb
    restart: always
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/log:/var/log/mongodb
    ports: 
      - "27017:27017"  